### ISSUE TITLE
The orientation of signin vertical textview not right

### ISSUE THREAD

**Issue by anubhakushwaha** [irfaan008/OnePageSigninSignup#1]
Earlier:
![whatsapp image 2017-02-02 at 3 13 18 pm](https://cloud.githubusercontent.com/assets/12814245/22544333/4e9eb432-e95a-11e6-89d7-ea8bbac8dd8e.jpeg)

After:
![whatsapp image 2017-02-02 at 3 13 18 pm 1](https://cloud.githubusercontent.com/assets/12814245/22544343/59bdec0c-e95a-11e6-95e6-4cfec131cb4d.jpeg)

Let me know if it's a valid issue.

**Comment by irfaan008** [comment]
Nice catch. Thanks for fix. Kindly raise a pull request so I could merge it with repository.

**Comment by anubhakushwaha** [comment]
@irfaan008 Done via #2

**Comment by irfaan008** [comment]
Thanks. Merged to master branch.
